"""
-*- coding: utf-8 -*-
@Author: li
@Email: lijianqiao2906@live.com
@FileName: __init__.py
@DateTime: 2025/06/20 00:00:00
@Docs: Pydantic校验模型模块初始化
"""

from .base import (
    # 类型别名
    ApiResponse,
    BaseCreateSchema,
    BaseQueryParams,
    BaseResponseSchema,
    # 基础模型
    BaseSchema,
    BaseUpdateSchema,
    # 批量操作模型
    BatchOperationRequest,
    BatchOperationResponse,
    BulkCreateRequest,
    BulkDeleteRequest,
    BulkUpdateRequest,
    ErrorResponse,
    # 响应模型
    IDResponse,
    ListResponse,
    PaginationInfo,
    PaginationResponse,
    StatusResponse,
    SuccessResponse,
    TimeRangeQuery,
)
from .brand import (
    BrandCreateRequest,
    BrandDetailResponse,
    BrandListResponse,
    BrandQueryParams,
    BrandResponse,
    BrandStatsResponse,
    BrandUpdateRequest,
)
from .config_diff import (
    ConfigChangeReportRequest,
    ConfigChangeReportResponse,
    ConfigDiffAnalysisRequest,
    ConfigDiffAnalysisResponse,
    ConfigDiffBatchAnalysisRequest,
    ConfigDiffCreateRequest,
    ConfigDiffDetailResponse,
    ConfigDiffListResponse,
    ConfigDiffQueryParams,
    ConfigDiffResponse,
    ConfigDiffStatsResponse,
    ConfigDiffTrendResponse,
    ConfigDiffUpdateRequest,
)
from .config_snapshot import (
    ConfigSnapshotBackupRequest,
    ConfigSnapshotBackupResponse,
    ConfigSnapshotBatchBackupResponse,
    ConfigSnapshotCleanupRequest,
    ConfigSnapshotCompareRequest,
    ConfigSnapshotCompareResponse,
    ConfigSnapshotCreateRequest,
    ConfigSnapshotDetailResponse,
    ConfigSnapshotListResponse,
    ConfigSnapshotQueryParams,
    ConfigSnapshotResponse,
    ConfigSnapshotRestoreRequest,
    ConfigSnapshotRestoreResponse,
    ConfigSnapshotStatsResponse,
    ConfigSnapshotUpdateRequest,
)
from .config_template import (
    ConfigTemplateCreateRequest,
    ConfigTemplateDetailResponse,
    ConfigTemplateListResponse,
    ConfigTemplateQueryParams,
    ConfigTemplateResponse,
    ConfigTemplateUpdateRequest,
    TemplateBatchExecuteResponse,
    TemplateCommandCreateRequest,
    TemplateCommandQueryParams,
    TemplateCommandResponse,
    TemplateCommandUpdateRequest,
    TemplateExecuteRequest,
    TemplateExecuteResponse,
    TemplateRenderRequest,
    TemplateRenderResponse,
    TemplateStatsResponse,
)
from .device import (
    DeviceBatchCommandResponse,
    DeviceBatchUpdateStatusRequest,
    DeviceCommandRequest,
    DeviceCommandResponse,
    DeviceConnectionRequest,
    DeviceConnectionResponse,
    DeviceCreateRequest,
    DeviceDetailResponse,
    DeviceListResponse,
    DeviceQueryParams,
    DeviceResponse,
    DeviceStatsResponse,
    DeviceUpdateRequest,
)
from .device_connection_status import (
    ConnectionAlertResponse,
    ConnectionHealthCheckRequest,
    ConnectionHealthCheckResponse,
    ConnectionMonitoringConfigRequest,
    ConnectionStatusStatsResponse,
    ConnectionTrendResponse,
    DeviceConnectionStatusCreateRequest,
    DeviceConnectionStatusQueryParams,
    DeviceConnectionStatusResponse,
    DeviceConnectionStatusUpdateRequest,
    DeviceReliabilityReportResponse,
)
from .device_group import (
    DeviceGroupBatchAssignRequest,
    DeviceGroupCreateRequest,
    DeviceGroupDetailResponse,
    DeviceGroupListResponse,
    DeviceGroupQueryParams,
    DeviceGroupResponse,
    DeviceGroupStatsResponse,
    DeviceGroupUpdateRequest,
)
from .device_model import (
    DeviceModelCreateRequest,
    DeviceModelDetailResponse,
    DeviceModelListResponse,
    DeviceModelQueryParams,
    DeviceModelResponse,
    DeviceModelStatsResponse,
    DeviceModelUpdateRequest,
)
from .operation_log import (
    OperationLogAnalysisResponse,
    OperationLogBatchDeleteRequest,
    OperationLogCreateRequest,
    OperationLogDetailResponse,
    OperationLogExportRequest,
    OperationLogListResponse,
    OperationLogQueryParams,
    OperationLogResponse,
    OperationLogStatsResponse,
    OperationLogTrendResponse,
)
from .region import (
    RegionCreateRequest,
    RegionDetailResponse,
    RegionListResponse,
    RegionQueryParams,
    RegionResponse,
    RegionStatsResponse,
    RegionUpdateRequest,
)
from .rollback_operation import (
    RollbackBatchExecuteRequest,
    RollbackBatchExecuteResponse,
    RollbackExecuteRequest,
    RollbackExecuteResponse,
    RollbackOperationCreateRequest,
    RollbackOperationDetailResponse,
    RollbackOperationListResponse,
    RollbackOperationQueryParams,
    RollbackOperationResponse,
    RollbackOperationUpdateRequest,
    RollbackReportRequest,
    RollbackReportResponse,
    RollbackStatsResponse,
    RollbackValidationRequest,
    RollbackValidationResponse,
)

__all__ = [
    # 基础模型
    "BaseSchema",
    "BaseCreateSchema",
    "BaseUpdateSchema",
    "BaseResponseSchema",
    "BaseQueryParams",
    "TimeRangeQuery",
    # 响应模型
    "IDResponse",
    "StatusResponse",
    "SuccessResponse",
    "ErrorResponse",
    "PaginationInfo",
    "PaginationResponse",
    # 批量操作模型
    "BatchOperationRequest",
    "BatchOperationResponse",
    "BulkCreateRequest",
    "BulkUpdateRequest",
    "BulkDeleteRequest",
    # 类型别名
    "ApiResponse",
    "ListResponse",
    # 区域相关
    "RegionCreateRequest",
    "RegionUpdateRequest",
    "RegionResponse",
    "RegionListResponse",
    "RegionDetailResponse",
    "RegionQueryParams",
    "RegionStatsResponse",
    # 品牌相关
    "BrandCreateRequest",
    "BrandUpdateRequest",
    "BrandResponse",
    "BrandListResponse",
    "BrandDetailResponse",
    "BrandQueryParams",
    "BrandStatsResponse",
    # 设备型号相关
    "DeviceModelCreateRequest",
    "DeviceModelUpdateRequest",
    "DeviceModelResponse",
    "DeviceModelListResponse",
    "DeviceModelDetailResponse",
    "DeviceModelQueryParams",
    "DeviceModelStatsResponse",
    # 设备分组相关
    "DeviceGroupCreateRequest",
    "DeviceGroupUpdateRequest",
    "DeviceGroupResponse",
    "DeviceGroupListResponse",
    "DeviceGroupDetailResponse",
    "DeviceGroupQueryParams",
    "DeviceGroupStatsResponse",
    "DeviceGroupBatchAssignRequest",
    # 设备相关
    "DeviceCreateRequest",
    "DeviceUpdateRequest",
    "DeviceResponse",
    "DeviceListResponse",
    "DeviceDetailResponse",
    "DeviceQueryParams",
    "DeviceConnectionRequest",
    "DeviceConnectionResponse",
    "DeviceCommandRequest",
    "DeviceCommandResponse",
    "DeviceBatchCommandResponse",
    "DeviceStatsResponse",
    "DeviceBatchUpdateStatusRequest",
    # 配置模板相关
    "ConfigTemplateCreateRequest",
    "ConfigTemplateUpdateRequest",
    "ConfigTemplateResponse",
    "ConfigTemplateListResponse",
    "ConfigTemplateDetailResponse",
    "ConfigTemplateQueryParams",
    "TemplateCommandCreateRequest",
    "TemplateCommandUpdateRequest",
    "TemplateCommandResponse",
    "TemplateCommandQueryParams",
    "TemplateExecuteRequest",
    "TemplateExecuteResponse",
    "TemplateBatchExecuteResponse",
    "TemplateRenderRequest",
    "TemplateRenderResponse",
    "TemplateStatsResponse",
    # 操作日志相关
    "OperationLogCreateRequest",
    "OperationLogResponse",
    "OperationLogListResponse",
    "OperationLogDetailResponse",
    "OperationLogQueryParams",
    "OperationLogStatsResponse",
    "OperationLogTrendResponse",
    "OperationLogExportRequest",
    "OperationLogBatchDeleteRequest",
    "OperationLogAnalysisResponse",
    # 设备连接状态相关
    "DeviceConnectionStatusCreateRequest",
    "DeviceConnectionStatusUpdateRequest",
    "DeviceConnectionStatusResponse",
    "DeviceConnectionStatusQueryParams",
    "ConnectionStatusStatsResponse",
    "ConnectionHealthCheckRequest",
    "ConnectionHealthCheckResponse",
    "ConnectionMonitoringConfigRequest",
    "ConnectionAlertResponse",
    "ConnectionTrendResponse",
    "DeviceReliabilityReportResponse",
    # 配置快照相关
    "ConfigSnapshotCreateRequest",
    "ConfigSnapshotUpdateRequest",
    "ConfigSnapshotResponse",
    "ConfigSnapshotListResponse",
    "ConfigSnapshotDetailResponse",
    "ConfigSnapshotQueryParams",
    "ConfigSnapshotCompareRequest",
    "ConfigSnapshotCompareResponse",
    "ConfigSnapshotBackupRequest",
    "ConfigSnapshotBackupResponse",
    "ConfigSnapshotBatchBackupResponse",
    "ConfigSnapshotRestoreRequest",
    "ConfigSnapshotRestoreResponse",
    "ConfigSnapshotStatsResponse",
    "ConfigSnapshotCleanupRequest",
    # 配置差异相关
    "ConfigDiffCreateRequest",
    "ConfigDiffUpdateRequest",
    "ConfigDiffResponse",
    "ConfigDiffListResponse",
    "ConfigDiffDetailResponse",
    "ConfigDiffQueryParams",
    "ConfigDiffAnalysisRequest",
    "ConfigDiffAnalysisResponse",
    "ConfigDiffBatchAnalysisRequest",
    "ConfigDiffTrendResponse",
    "ConfigDiffStatsResponse",
    "ConfigChangeReportRequest",
    "ConfigChangeReportResponse",
    # 回滚操作相关
    "RollbackOperationCreateRequest",
    "RollbackOperationUpdateRequest",
    "RollbackOperationResponse",
    "RollbackOperationListResponse",
    "RollbackOperationDetailResponse",
    "RollbackOperationQueryParams",
    "RollbackExecuteRequest",
    "RollbackExecuteResponse",
    "RollbackBatchExecuteRequest",
    "RollbackBatchExecuteResponse",
    "RollbackValidationRequest",
    "RollbackValidationResponse",
    "RollbackStatsResponse",
    "RollbackReportRequest",
    "RollbackReportResponse",
]
